name = "portfolio-tracker"
main = ".open-next/worker.js"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "8e567040-fecb-428d-b75d-e29ce0e73b31"

[[kv_namespaces]]
binding = "PRICE_CACHE"
id = "86f512e06ba1486dad6ede0080ecf379"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
